spring:
  application:
    name: usercenter-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        import-check:
          enabled: false